---
apiVersion: v1
kind: Service
metadata:
  name: fbservice
  labels:
    app: div
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012
  selector:
    app: fb
